env:
  browser: true
  es2021: true
extends:
  - "airbnb-base"
  - "prettier"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
globals:
  $: readonly

rules:
  no-alert: off # OK: A lot easier than coding up new UI.
  no-console: # OK: console.log is fine for debugging, but we don't want to keep it around indefinitely.
    - error # Also make sure that warnings and errors are marked as such.
    - { allow: ["warn", "error"] }
