inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "storage/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Exclude:
    - "spec/system/data_migration/*"

Metrics/AbcSize:
  Exclude:
    - "app/mailers/tigerdata_mailer.rb"

Metrics/BlockLength:
  Exclude:
    - "app/models/mediaflux/http/asset_create_request.rb"
    - "config/environments/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
  Max: 40 # default: 25

Metrics/ClassLength:
  Max: 150 # default: 100

Metrics/MethodLength:
  Max: 15 # default: 10
  Exclude:
    - "app/mailers/tigerdata_mailer.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude: []

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false
