inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "storage/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Exclude:
    - "spec/system/data_migration/*"

Metrics/AbcSize:
  Exclude:
    - "app/mailers/tigerdata_mailer.rb"

Metrics/BlockLength:
  Exclude:
    - "app/models/mediaflux/http/asset_create_request.rb"
    - "config/environments/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
  Max: 40 # default: 25

Metrics/ClassLength:
  Max: 150 # default: 100
  Exclude:
    - app/models/media_flux_client.rb

Metrics/MethodLength:
  Max: 15 # default: 10
  Exclude:
    - app/models/media_flux_client.rb
    - "app/mailers/tigerdata_mailer.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude: []

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/UnknownEnv:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/system/**/*"

RSpec/ExampleLength:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: true
Rails/AddColumnIndex: # new in 2.11
  Enabled: true
Rails/AfterCommitOverride: # new in 2.8
  Enabled: true
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: true
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: true
Rails/DuplicateAssociation: # new in 2.14
  Enabled: true
Rails/DuplicateScope: # new in 2.14
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: true
Rails/ExpandedDateRange: # new in 2.11
  Enabled: true
Rails/FindById: # new in 2.7
  Enabled: true
Rails/I18nLazyLookup: # new in 2.14
  Enabled: true
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: true
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: true
Rails/Inquiry: # new in 2.7
  Enabled: true
Rails/MailerName: # new in 2.7
  Enabled: true
Rails/MatchRoute: # new in 2.7
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/NegateInclude: # new in 2.7
  Enabled: true
Rails/Pluck: # new in 2.7
  Enabled: true
Rails/PluckInWhere: # new in 2.7
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Rails/RedundantTravelBack: # new in 2.12
  Enabled: true
Rails/RenderInline: # new in 2.7
  Enabled: true
Rails/RenderPlainText: # new in 2.7
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Rails/RootPublicPath: # new in 2.15
  Enabled: true
Rails/ShortI18n: # new in 2.7
  Enabled: true
Rails/SquishedSQLHeredocs: # new in 2.8
  Enabled: true
Rails/StripHeredoc: # new in 2.15
  Enabled: true
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: true
Rails/ToFormattedS: # new in 2.15
  Enabled: true
Rails/TransactionExitStatement: # new in 2.14
  Enabled: true
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: true
Rails/WhereEquals: # new in 2.9
  Enabled: true
Rails/WhereExists: # new in 2.7
  Enabled: true
Rails/WhereNot: # new in 2.8
  Enabled: true
