services:
  mediaflux:
    image: "pulibraryrdss/mediaflux_dev:v0.3.7" 
    ports:
      - "8888:80"
    networks:
      my_network:
        mac_address: "02:42:ac:11:00:02"
    

  database:
    image: "postgres:13"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  my_network: