# frozen_string_literal: true
module Mediaflux
  class Session
    attr_reader :token

    # Constructor
    # @param use_ssl [Boolean] determines whether or not connections to the Mediaflux server API are over the TLS/SSL
    # @param http_client [Net::HTTP] HTTP client for transmitting requests to the Mediaflux server API
    def initialize(use_ssl: false, http_client: nil)
      @http_client = http_client || Mediaflux::Http::Request.build_http_client
      @http_client.use_ssl = use_ssl
    end

    # Authenticates against the Mediaflux server API
    # @return [String] the session token generated by the Mediaflux server
    def logon
      logon_request = Mediaflux::Http::LogonRequest.new(http_client: @http_client)
      logon_request.resolve
      @token = logon_request.session_token
    end

    # Determines whether or not the current session has been authenticated
    # @return [Boolean]
    def authenticated?
      @token.present?
    end

    # Retrieves all Collections within the default namespace from the Mediaflux server API
    # @return [Array<Collection>] the collections constructed from the XML-serialized data in the server response
    def collections
      logon unless authenticated?

      collection_list_request = Mediaflux::Http::CollectionListRequest.new(http_client: @http_client, session_token: @token)
      response_xml = collection_list_request.response_xml
      Collection.build_from_response(xml: response_xml)
    end
  end
end
