---
default: &default
  prefix: '<%= ENV["DATACITE_PREFIX"]  ||  10.0000 %>'
  user: <%= ENV["DATACITE_USER"] || "" %>
  password: <%= ENV["DATACITE_PASSWORD"] || "" %>
  host: <%= ENV["DATACITE_HOST"] || "api.datacite.org" %>
  doi_url: "https://handle.stage.datacite.org/"
production:
  <<: *default
  prefix: "10.60803"
  # Use the TigerData specific settings
  doi_url: "https://doi.org/"
qa:
  <<: *default
staging:
  <<: *default
ci:
  <<: *default
development:
  <<: *default
test:
  <<: *default
