---
development:
  title: As an approved tester-trainer
  body: You may select another role to emulate
  alt_title: As an approved tester-trainer
  alt_body: You are currently emulating
qa:
  title: As an approved tester-trainer
  body: You may select another role to emulate
  alt_title: As an approved tester-trainer
  alt_body: You are currently emulating
staging:
  title: As an approved tester-trainer
  body: You may select another role to emulate
  alt_title: As an approved tester-trainer
  alt_body: You are currently emulating
test:
  title: As an approved tester-trainer
  body: You may select another role to emulate
  alt_title: As an approved tester-trainer
  alt_body: You are currently emulating
