production: &default
  storage_capacity:
    size:
      requested: 500
      approved: null
    unit:
      requested: "GB"
      approved: null
  storage_performance_expectations:
    requested: "Standard"
    approved: null
  project_purpose: "Research"
qa:
  <<: *default
staging:
  <<: *default
ci:
  <<: *default
development:
  <<: *default
test:
  <<: *default
