---
name: Run test suite against Mflux-CI
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1-5
jobs:
  daily_check:
    runs-on: ubuntu-latest
    steps:
      - name: Every weekday morning at 8:00 AM
        if: github.event.schedule == '0 8 * * 1-5'
        id: tigerdata_ci_trigger
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.Automated_Ci_Test }}
