---
name: Run test suite against Mflux-CI
on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
jobs:
  daily_check:
    runs-on: ubuntu-latest
    steps:
      - name: Run CircleCI Pipeline after merging to main
        id: tigerdata_ci_trigger
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: "TigerData-App"
        env:
          CCI_TOKEN: ${{ secrets.Automated_Ci_Test }}
