---
name: Deploy API docs to GitHub Pages
on:
  push:
    branches: ["main"]
    # paths:
    #   - '.github/workflows/pages.yml'
    #   - '.yardopts'
    #   - 'lib/**'
    #   - 'Gemfile'
    #   - '**.txt'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy_yard:
    # the deploy environment (not to be confused with env)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Build and deploy YARD
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec yard
        shell: bash
      - uses: actions/configure-pages@v5
      - uses: actions/upload-artifact@v4
        with:
          # Yard puts everything into a folder called 'doc' by default
          path: "doc"
      - id: deployment
        uses: actions/deploy-pages@v4
